/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as DetectionRouteImport } from './routes/detection'
import { Route as EnforcementVerificationRouteImport } from './routes/enforcement-verification'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as ExplainabilityRouteImport } from './routes/explainability'
import { Route as MonitorRouteImport } from './routes/monitor'
import { Route as PayloadInspectorRouteImport } from './routes/payload-inspector'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as QuarantineRouteImport } from './routes/quarantine'
import { Route as ResearchEvalRouteImport } from './routes/research-eval'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as SensitivityConfigRouteImport } from './routes/sensitivity-config'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as StatusRouteImport } from './routes/status'
import { Route as TopologyRouteImport } from './routes/topology'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectionRoute = DetectionRouteImport.update({
  id: '/detection',
  path: '/detection',
  getParentRoute: () => rootRouteImport,
} as any)
const EnforcementVerificationRoute = EnforcementVerificationRouteImport.update({
  id: '/enforcement-verification',
  path: '/enforcement-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainabilityRoute = ExplainabilityRouteImport.update({
  id: '/explainability',
  path: '/explainability',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorRoute = MonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const PayloadInspectorRoute = PayloadInspectorRouteImport.update({
  id: '/payload-inspector',
  path: '/payload-inspector',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const QuarantineRoute = QuarantineRouteImport.update({
  id: '/quarantine',
  path: '/quarantine',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchEvalRoute = ResearchEvalRouteImport.update({
  id: '/research-eval',
  path: '/research-eval',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const SensitivityConfigRoute = SensitivityConfigRouteImport.update({
  id: '/sensitivity-config',
  path: '/sensitivity-config',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const TopologyRoute = TopologyRouteImport.update({
  id: '/topology',
  path: '/topology',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/compliance': typeof ComplianceRoute
  '/decisions': typeof DecisionsRoute
  '/detection': typeof DetectionRoute
  '/enforcement-verification': typeof EnforcementVerificationRoute
  '/evaluation': typeof EvaluationRoute
  '/explainability': typeof ExplainabilityRoute
  '/monitor': typeof MonitorRoute
  '/payload-inspector': typeof PayloadInspectorRoute
  '/permissions': typeof PermissionsRoute
  '/playground': typeof PlaygroundRoute
  '/policies': typeof PoliciesRoute
  '/quarantine': typeof QuarantineRoute
  '/research-eval': typeof ResearchEvalRoute
  '/risk': typeof RiskRoute
  '/sensitivity-config': typeof SensitivityConfigRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/status': typeof StatusRoute
  '/topology': typeof TopologyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/compliance': typeof ComplianceRoute
  '/decisions': typeof DecisionsRoute
  '/detection': typeof DetectionRoute
  '/enforcement-verification': typeof EnforcementVerificationRoute
  '/evaluation': typeof EvaluationRoute
  '/explainability': typeof ExplainabilityRoute
  '/monitor': typeof MonitorRoute
  '/payload-inspector': typeof PayloadInspectorRoute
  '/permissions': typeof PermissionsRoute
  '/playground': typeof PlaygroundRoute
  '/policies': typeof PoliciesRoute
  '/quarantine': typeof QuarantineRoute
  '/research-eval': typeof ResearchEvalRoute
  '/risk': typeof RiskRoute
  '/sensitivity-config': typeof SensitivityConfigRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/status': typeof StatusRoute
  '/topology': typeof TopologyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/compliance': typeof ComplianceRoute
  '/decisions': typeof DecisionsRoute
  '/detection': typeof DetectionRoute
  '/enforcement-verification': typeof EnforcementVerificationRoute
  '/evaluation': typeof EvaluationRoute
  '/explainability': typeof ExplainabilityRoute
  '/monitor': typeof MonitorRoute
  '/payload-inspector': typeof PayloadInspectorRoute
  '/permissions': typeof PermissionsRoute
  '/playground': typeof PlaygroundRoute
  '/policies': typeof PoliciesRoute
  '/quarantine': typeof QuarantineRoute
  '/research-eval': typeof ResearchEvalRoute
  '/risk': typeof RiskRoute
  '/sensitivity-config': typeof SensitivityConfigRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/status': typeof StatusRoute
  '/topology': typeof TopologyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/compliance'
    | '/decisions'
    | '/detection'
    | '/enforcement-verification'
    | '/evaluation'
    | '/explainability'
    | '/monitor'
    | '/payload-inspector'
    | '/permissions'
    | '/playground'
    | '/policies'
    | '/quarantine'
    | '/research-eval'
    | '/risk'
    | '/sensitivity-config'
    | '/settings'
    | '/simulator'
    | '/status'
    | '/topology'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/compliance'
    | '/decisions'
    | '/detection'
    | '/enforcement-verification'
    | '/evaluation'
    | '/explainability'
    | '/monitor'
    | '/payload-inspector'
    | '/permissions'
    | '/playground'
    | '/policies'
    | '/quarantine'
    | '/research-eval'
    | '/risk'
    | '/sensitivity-config'
    | '/settings'
    | '/simulator'
    | '/status'
    | '/topology'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/compliance'
    | '/decisions'
    | '/detection'
    | '/enforcement-verification'
    | '/evaluation'
    | '/explainability'
    | '/monitor'
    | '/payload-inspector'
    | '/permissions'
    | '/playground'
    | '/policies'
    | '/quarantine'
    | '/research-eval'
    | '/risk'
    | '/sensitivity-config'
    | '/settings'
    | '/simulator'
    | '/status'
    | '/topology'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  ComplianceRoute: typeof ComplianceRoute
  DecisionsRoute: typeof DecisionsRoute
  DetectionRoute: typeof DetectionRoute
  EnforcementVerificationRoute: typeof EnforcementVerificationRoute
  EvaluationRoute: typeof EvaluationRoute
  ExplainabilityRoute: typeof ExplainabilityRoute
  MonitorRoute: typeof MonitorRoute
  PayloadInspectorRoute: typeof PayloadInspectorRoute
  PermissionsRoute: typeof PermissionsRoute
  PlaygroundRoute: typeof PlaygroundRoute
  PoliciesRoute: typeof PoliciesRoute
  QuarantineRoute: typeof QuarantineRoute
  ResearchEvalRoute: typeof ResearchEvalRoute
  RiskRoute: typeof RiskRoute
  SensitivityConfigRoute: typeof SensitivityConfigRoute
  SettingsRoute: typeof SettingsRoute
  SimulatorRoute: typeof SimulatorRoute
  StatusRoute: typeof StatusRoute
  TopologyRoute: typeof TopologyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detection': {
      id: '/detection'
      path: '/detection'
      fullPath: '/detection'
      preLoaderRoute: typeof DetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enforcement-verification': {
      id: '/enforcement-verification'
      path: '/enforcement-verification'
      fullPath: '/enforcement-verification'
      preLoaderRoute: typeof EnforcementVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explainability': {
      id: '/explainability'
      path: '/explainability'
      fullPath: '/explainability'
      preLoaderRoute: typeof ExplainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor': {
      id: '/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof MonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payload-inspector': {
      id: '/payload-inspector'
      path: '/payload-inspector'
      fullPath: '/payload-inspector'
      preLoaderRoute: typeof PayloadInspectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quarantine': {
      id: '/quarantine'
      path: '/quarantine'
      fullPath: '/quarantine'
      preLoaderRoute: typeof QuarantineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-eval': {
      id: '/research-eval'
      path: '/research-eval'
      fullPath: '/research-eval'
      preLoaderRoute: typeof ResearchEvalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensitivity-config': {
      id: '/sensitivity-config'
      path: '/sensitivity-config'
      fullPath: '/sensitivity-config'
      preLoaderRoute: typeof SensitivityConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topology': {
      id: '/topology'
      path: '/topology'
      fullPath: '/topology'
      preLoaderRoute: typeof TopologyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  ComplianceRoute: ComplianceRoute,
  DecisionsRoute: DecisionsRoute,
  DetectionRoute: DetectionRoute,
  EnforcementVerificationRoute: EnforcementVerificationRoute,
  EvaluationRoute: EvaluationRoute,
  ExplainabilityRoute: ExplainabilityRoute,
  MonitorRoute: MonitorRoute,
  PayloadInspectorRoute: PayloadInspectorRoute,
  PermissionsRoute: PermissionsRoute,
  PlaygroundRoute: PlaygroundRoute,
  PoliciesRoute: PoliciesRoute,
  QuarantineRoute: QuarantineRoute,
  ResearchEvalRoute: ResearchEvalRoute,
  RiskRoute: RiskRoute,
  SensitivityConfigRoute: SensitivityConfigRoute,
  SettingsRoute: SettingsRoute,
  SimulatorRoute: SimulatorRoute,
  StatusRoute: StatusRoute,
  TopologyRoute: TopologyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
